#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d term firefox dev qemu torrent 

#BSPWM coloring
bspc config normal_border_color     "#232730"
bspc config active_border_color     "#1a1d23"
bspc config focused_border_color    "#3c4252"
bspc config presel_feedback_color   "#5e81ac"
#bspc config urgent_border_color    "#dd2727"

bspc config border_width        0
bspc config window_gap          10
bspc config top_padding         27

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop firefox -l monocle

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a jetbrains-idea-ce desktop='^3' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
picom --inactive-dim 0.3 &
$HOME/.fehbg &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &
xsetroot -cursor_name left_ptr &
numlockx

